version: '3'

services:
  postgres:
        restart: unless-stopped
        image: postgres:15
        env_file:
          - .env
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        networks:
          - bobik300_network

  django:
        restart: unless-stopped
        build:
          context: .
          dockerfile: Dockerfile
        env_file:
          - .env
        ports:
          - "8000:8000"
        volumes:
          - static_volume:/app/static
          - media_volume:/app/media
        networks:
          - bobik300_network
        depends_on:
          - postgres


volumes:
    static_volume:
    media_volume:
    postgres_data:
networks:
  bobik300_network:
    driver: bridge