version: '3'

services:
  postgres:
    restart: unless-stopped
    image: postgres:13.1-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data # save postgresql data between container restarts
    networks:
      - reboot_network
    ports:
      - "5432:5432"

  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerFile
    env_file:
      - ./.env
    volumes:
      - static_volume:/core/static
      - media_volume:/core/media
    networks:
      - reboot_network
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/DockerFile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/default.conf
    networks:
      - reboot_network
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  reboot_network:
    driver: bridge
