version: '3'

services:
  project_postgres:
    restart: unless-stopped
    image: postgres:13.1-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    profiles:
      - local_dev
      - full_run
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - project_network

  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    profiles:
      - full_run
    networks:
      - project_network
    depends_on:
      - project_postgres

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  project_network:
    driver: bridge
