version: '3'

services:
  postgres:
        restart: unless-stopped
        image: postgres:15
        env_file:
          - ./.env
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        networks:
          - project_network

  django:
        restart: unless-stopped
        build:
          context: .
          dockerfile: Dockerfile
        env_file:
          - ./.env
        volumes:
          - static_volume:/app/static
          - media_volume:/app/media
        networks:
          - project_network
        depends_on:
          - postgres


volumes:
    static_volume:
    media_volume:
    postgres_data:
networks:
  project_network:
    driver: bridge