FROM python:3.10

ENV PYTHONBUFFERED=1 \
    POETRY_VERSION=1.4.2 \
    POETRY_VIRTUALENVS_CREATE="false"

RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /python-kublo

COPY pyproject.toml poetry.lock backend/docker-entrypoint.sh ./

RUN poetry install --no-interaction --no-ansi --no-dev

COPY . /python-kublo
EXPOSE 8000
RUN chmod +x docker-entrypoint.sh
ENTRYPOINT ["./docker-entrypoint.sh"]
