# Generated by Django 4.2.4 on 2023-09-06 08:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_api', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_code', models.CharField(max_length=10, unique=True)),
                ('investment_sector', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Investment sector should be at least 2 characters long')])),
                ('deposit_term', models.DurationField(default=datetime.timedelta(days=30))),
                ('total_deposit_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dividend_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('partners', models.ManyToManyField(blank=True, related_name='partner', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['partner_code'], name='cabinet_api_partner_7c4a17_idx')],
            },
        ),
    ]
