# Generated by Django 4.2.4 on 2023-10-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_api', '0004_personalaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaccount',
            name='deposit_term',
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='deposit_term_end',
            field=models.DateField(help_text='End date of investment term', null=True),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='deposit_term_start',
            field=models.DateField(help_text='Start date of investment term', null=True),
        ),
    ]
