# Generated by Django 4.2.4 on 2023-10-14 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_api', '0005_remove_personalaccount_deposit_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='investment_sector',
            field=models.CharField(choices=[('informational_technologies', 'Informational Technologies'), ('technology', 'Technology'), ('healthcare', 'Healthcare'), ('financials', 'Financials'), ('consumer', 'Consumer'), ('industrials', 'Industrials')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='partner_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='Partner code has to be exactly 10 characters long')]),
        ),
    ]
