# Generated by Django 4.2.4 on 2023-09-10 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_investmentsector_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentsector',
            name='sector',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Investment sector characters number should be greater than 2!')]),
        ),
    ]
