# Generated by Django 4.2.4 on 2023-08-27 15:59

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4)])),
                ('partnership_code', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('investment_sector', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('deposit_term', models.DateTimeField()),
                ('total_deposit_amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate', models.DecimalField(decimal_places=5, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_dividends_amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('referral_partners_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]), size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
