# Generated by Django 4.2.4 on 2023-08-27 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='referral_partners_list',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
